//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_1C.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ОписаниеСтроки", Namespace="http://www.sample-package.org", ItemName="Значения")]
    [System.SerializableAttribute()]
    public class ОписаниеСтроки : System.Collections.Generic.List<test_1C.ServiceReference1.ОписаниеЗначения> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ОписаниеЗначения", Namespace="http://www.sample-package.org")]
    [System.SerializableAttribute()]
    public partial class ОписаниеЗначения : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string НаименованиеField;
        
        private string ЗначениеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Наименование {
            get {
                return this.НаименованиеField;
            }
            set {
                if ((object.ReferenceEquals(this.НаименованиеField, value) != true)) {
                    this.НаименованиеField = value;
                    this.RaisePropertyChanged("Наименование");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Значение {
            get {
                return this.ЗначениеField;
            }
            set {
                if ((object.ReferenceEquals(this.ЗначениеField, value) != true)) {
                    this.ЗначениеField = value;
                    this.RaisePropertyChanged("Значение");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="СписокТаблиц", Namespace="http://www.sample-package.org", ItemName="Таблицы")]
    [System.SerializableAttribute()]
    public class СписокТаблиц : System.Collections.Generic.List<test_1C.ServiceReference1.ОписаниеТаблицы> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ОписаниеТаблицы", Namespace="http://www.sample-package.org", ItemName="Строки")]
    [System.SerializableAttribute()]
    public class ОписаниеТаблицы : System.Collections.Generic.List<test_1C.ServiceReference1.ОписаниеСтроки> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sample-package.org", ConfigurationName="ServiceReference1.WebServiceCommonPortType")]
    public interface WebServiceCommonPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:WebServiceCommonFunction", ReplyAction="*")]
        test_1C.ServiceReference1.WebServiceCommonFunctionResponse WebServiceCommonFunction(test_1C.ServiceReference1.WebServiceCommonFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:WebServiceCommonFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.WebServiceCommonFunctionResponse> WebServiceCommonFunctionAsync(test_1C.ServiceReference1.WebServiceCommonFunctionRequest request);
        
        // CODEGEN: Generating message contract since element name Артикул from namespace http://www.sample-package.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:Тест", ReplyAction="*")]
        test_1C.ServiceReference1.ТестResponse Тест(test_1C.ServiceReference1.ТестRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:Тест", ReplyAction="*")]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.ТестResponse> ТестAsync(test_1C.ServiceReference1.ТестRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:Upload", ReplyAction="*")]
        test_1C.ServiceReference1.UploadResponse Upload(test_1C.ServiceReference1.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sample-package.org#WebServiceCommon:Upload", ReplyAction="*")]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.UploadResponse> UploadAsync(test_1C.ServiceReference1.UploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceCommonFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceCommonFunction", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.WebServiceCommonFunctionRequestBody Body;
        
        public WebServiceCommonFunctionRequest() {
        }
        
        public WebServiceCommonFunctionRequest(test_1C.ServiceReference1.WebServiceCommonFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class WebServiceCommonFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FunctionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public test_1C.ServiceReference1.ОписаниеСтроки Parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public test_1C.ServiceReference1.СписокТаблиц Tables;
        
        public WebServiceCommonFunctionRequestBody() {
        }
        
        public WebServiceCommonFunctionRequestBody(string UserName, string FunctionName, test_1C.ServiceReference1.ОписаниеСтроки Parameters, test_1C.ServiceReference1.СписокТаблиц Tables) {
            this.UserName = UserName;
            this.FunctionName = FunctionName;
            this.Parameters = Parameters;
            this.Tables = Tables;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceCommonFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceCommonFunctionResponse", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.WebServiceCommonFunctionResponseBody Body;
        
        public WebServiceCommonFunctionResponse() {
        }
        
        public WebServiceCommonFunctionResponse(test_1C.ServiceReference1.WebServiceCommonFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class WebServiceCommonFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public test_1C.ServiceReference1.ОписаниеСтроки Parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public test_1C.ServiceReference1.СписокТаблиц Tables;
        
        public WebServiceCommonFunctionResponseBody() {
        }
        
        public WebServiceCommonFunctionResponseBody(string @return, test_1C.ServiceReference1.ОписаниеСтроки Parameters, test_1C.ServiceReference1.СписокТаблиц Tables) {
            this.@return = @return;
            this.Parameters = Parameters;
            this.Tables = Tables;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ТестRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Тест", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.ТестRequestBody Body;
        
        public ТестRequest() {
        }
        
        public ТестRequest(test_1C.ServiceReference1.ТестRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class ТестRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public test_1C.ServiceReference1.ОписаниеЗначения Артикул;
        
        public ТестRequestBody() {
        }
        
        public ТестRequestBody(test_1C.ServiceReference1.ОписаниеЗначения Артикул) {
            this.Артикул = Артикул;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ТестResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ТестResponse", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.ТестResponseBody Body;
        
        public ТестResponse() {
        }
        
        public ТестResponse(test_1C.ServiceReference1.ТестResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class ТестResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ТестResponseBody() {
        }
        
        public ТестResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upload", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.UploadRequestBody Body;
        
        public UploadRequest() {
        }
        
        public UploadRequest(test_1C.ServiceReference1.UploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class UploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Prefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Struktura;
        
        public UploadRequestBody() {
        }
        
        public UploadRequestBody(string GUID, string Prefix, string Struktura) {
            this.GUID = GUID;
            this.Prefix = Prefix;
            this.Struktura = Struktura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadResponse", Namespace="http://www.sample-package.org", Order=0)]
        public test_1C.ServiceReference1.UploadResponseBody Body;
        
        public UploadResponse() {
        }
        
        public UploadResponse(test_1C.ServiceReference1.UploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sample-package.org")]
    public partial class UploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Prefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Struktura;
        
        public UploadResponseBody() {
        }
        
        public UploadResponseBody(string @return, string Prefix, string Struktura) {
            this.@return = @return;
            this.Prefix = Prefix;
            this.Struktura = Struktura;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCommonPortTypeChannel : test_1C.ServiceReference1.WebServiceCommonPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCommonPortTypeClient : System.ServiceModel.ClientBase<test_1C.ServiceReference1.WebServiceCommonPortType>, test_1C.ServiceReference1.WebServiceCommonPortType {
        
        public WebServiceCommonPortTypeClient() {
        }
        
        public WebServiceCommonPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCommonPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCommonPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCommonPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_1C.ServiceReference1.WebServiceCommonFunctionResponse test_1C.ServiceReference1.WebServiceCommonPortType.WebServiceCommonFunction(test_1C.ServiceReference1.WebServiceCommonFunctionRequest request) {
            return base.Channel.WebServiceCommonFunction(request);
        }
        
        public string WebServiceCommonFunction(string UserName, string FunctionName, ref test_1C.ServiceReference1.ОписаниеСтроки Parameters, ref test_1C.ServiceReference1.СписокТаблиц Tables) {
            test_1C.ServiceReference1.WebServiceCommonFunctionRequest inValue = new test_1C.ServiceReference1.WebServiceCommonFunctionRequest();
            inValue.Body = new test_1C.ServiceReference1.WebServiceCommonFunctionRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.FunctionName = FunctionName;
            inValue.Body.Parameters = Parameters;
            inValue.Body.Tables = Tables;
            test_1C.ServiceReference1.WebServiceCommonFunctionResponse retVal = ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).WebServiceCommonFunction(inValue);
            Parameters = retVal.Body.Parameters;
            Tables = retVal.Body.Tables;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.WebServiceCommonFunctionResponse> test_1C.ServiceReference1.WebServiceCommonPortType.WebServiceCommonFunctionAsync(test_1C.ServiceReference1.WebServiceCommonFunctionRequest request) {
            return base.Channel.WebServiceCommonFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_1C.ServiceReference1.WebServiceCommonFunctionResponse> WebServiceCommonFunctionAsync(string UserName, string FunctionName, test_1C.ServiceReference1.ОписаниеСтроки Parameters, test_1C.ServiceReference1.СписокТаблиц Tables) {
            test_1C.ServiceReference1.WebServiceCommonFunctionRequest inValue = new test_1C.ServiceReference1.WebServiceCommonFunctionRequest();
            inValue.Body = new test_1C.ServiceReference1.WebServiceCommonFunctionRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.FunctionName = FunctionName;
            inValue.Body.Parameters = Parameters;
            inValue.Body.Tables = Tables;
            return ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).WebServiceCommonFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_1C.ServiceReference1.ТестResponse test_1C.ServiceReference1.WebServiceCommonPortType.Тест(test_1C.ServiceReference1.ТестRequest request) {
            return base.Channel.Тест(request);
        }
        
        public string Тест(test_1C.ServiceReference1.ОписаниеЗначения Артикул) {
            test_1C.ServiceReference1.ТестRequest inValue = new test_1C.ServiceReference1.ТестRequest();
            inValue.Body = new test_1C.ServiceReference1.ТестRequestBody();
            inValue.Body.Артикул = Артикул;
            test_1C.ServiceReference1.ТестResponse retVal = ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).Тест(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.ТестResponse> test_1C.ServiceReference1.WebServiceCommonPortType.ТестAsync(test_1C.ServiceReference1.ТестRequest request) {
            return base.Channel.ТестAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_1C.ServiceReference1.ТестResponse> ТестAsync(test_1C.ServiceReference1.ОписаниеЗначения Артикул) {
            test_1C.ServiceReference1.ТестRequest inValue = new test_1C.ServiceReference1.ТестRequest();
            inValue.Body = new test_1C.ServiceReference1.ТестRequestBody();
            inValue.Body.Артикул = Артикул;
            return ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).ТестAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_1C.ServiceReference1.UploadResponse test_1C.ServiceReference1.WebServiceCommonPortType.Upload(test_1C.ServiceReference1.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public string Upload(string GUID, ref string Prefix, ref string Struktura) {
            test_1C.ServiceReference1.UploadRequest inValue = new test_1C.ServiceReference1.UploadRequest();
            inValue.Body = new test_1C.ServiceReference1.UploadRequestBody();
            inValue.Body.GUID = GUID;
            inValue.Body.Prefix = Prefix;
            inValue.Body.Struktura = Struktura;
            test_1C.ServiceReference1.UploadResponse retVal = ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).Upload(inValue);
            Prefix = retVal.Body.Prefix;
            Struktura = retVal.Body.Struktura;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_1C.ServiceReference1.UploadResponse> test_1C.ServiceReference1.WebServiceCommonPortType.UploadAsync(test_1C.ServiceReference1.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_1C.ServiceReference1.UploadResponse> UploadAsync(string GUID, string Prefix, string Struktura) {
            test_1C.ServiceReference1.UploadRequest inValue = new test_1C.ServiceReference1.UploadRequest();
            inValue.Body = new test_1C.ServiceReference1.UploadRequestBody();
            inValue.Body.GUID = GUID;
            inValue.Body.Prefix = Prefix;
            inValue.Body.Struktura = Struktura;
            return ((test_1C.ServiceReference1.WebServiceCommonPortType)(this)).UploadAsync(inValue);
        }
    }
}
